[workspace]

members = [
    'bina-ecs',
    'bina',
    'bina-macros',
    'bina-app',
    'bina-graphics'
]

[workspace.dependencies]
static_assertions = "1.1"
log = "0.4"
fxhash = "0.2"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 2