[package]
name = "bina-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bina-ecs = { path = "../bina-ecs" }
quote = "1.0.*"
syn = "2.0.*"
proc-macro2 = "1.0.*"

[lib]
proc-macro = true